---
settings:
  name: BlueXP
  platform: cloud
  search: cloud-manager-relnotes,cloud-manager-setup-admin,cloud-manager-cloud-volumes-ontap,cloud-manager-ontap-onprem,cloud-manager-azure-netapp-files,cloud-manager-fsx-ontap,cloud-manager-cloud-volumes-service-aws,cloud-manager-cloud-volumes-service-gcp,cloud-manager-kubernetes,cloud-manager-app-template,cloud-manager-backup-restore,cloud-manager-sync,cloud-manager-data-sense,cloud-manager-tiering,cloud-manager-ransomware,cloud-manager-replication,cloud-manager-file-cache,cloud-manager-compute,cloud-manager-automation,cloud-volumes-ontap-relnotes,cloud-manager-storagegrid,cloud-manager-e-series,bluexp-s3-storage
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: 所有BlueXP文档
    url: "/index.html"
product-family:
  sidebarlinks:
  - title: 全部
    tags: all
    class: active
  - title: API
    tags: api
  - title: 连接器和帐户
    tags: admin
  - title: 扩展
    tags: extension
  - title: 监管
    tags: governance
  - title: 运行状况
    tags: health
  - title: 洞察力
    tags: insights
  - title: 移动性
    tags: mobility
  - title: 保护
    tags: protection
  - title: 存储
    tags: storage
  tiles:
  - title: 欢迎使用BlueXP
    icon: "./media/icon-docs.png"
    url: concept-overview.html
    summary: 了解有关BlueXP的简介。
    tags: all
  - title: 设置和管理
    icon: "./media/icon-admin.png"
    url: https://docs.netapp.com/us-en/cloud-manager-setup-admin/index.html
    summary: 了解如何开始使用BlueXP并管理连接器、帐户等。
    tags: all, admin
  - title: 发行说明
    icon: "./media/icon-docs.png"
    url: https://docs.netapp.com/us-en/cloud-manager-relnotes/index.html
    summary: 了解整个BlueXP中的新增功能。
    tags: all
  - title: 适用于 NetApp ONTAP 的 Amazon FSX
    icon: "./media/icon-fsx.png"
    url: https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html
    summary: 将 ONTAP 的全部功能用作原生 AWS 管理的服务。
    tags: all, storage, aws
  - title: Amazon S3存储
    icon: "./media/icon-s3.png"
    url: https://docs.netapp.com/us-en/bluexp-s3-storage/index.html
    summary: 发现并管理AWS帐户中的Amazon S3存储分段。
    tags: all, storage, aws
  - title: API
    icon: "./media/icon-api.png"
    url: https://docs.netapp.com/us-en/cloud-manager-automation/index.html
    summary: 以编程方式管理基于云的资源。
    tags: all, api
  - title: Azure NetApp Files
    icon: "./media/icon-anf.png"
    url: https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/index.html
    summary: 适用于核心业务应用程序的高性能文件存储服务。
    tags: all, storage, azure
  - title: 备份和恢复(Cloud Backup)
    icon: "./media/icon-backup.png"
    url: https://docs.netapp.com/us-en/cloud-manager-backup-restore/index.html
    summary: 备份和还原云和内部数据。
    tags: all, aws, azure, gcp, protection
  - title: 分类(云数据感知)
    icon: "./media/icon-data-sense.png"
    url: https://docs.netapp.com/us-en/cloud-manager-data-sense/index.html
    summary: 让您的应用程序数据和云环境做好隐私准备。
    tags: all, governance, aws, azure, gcp
  - title: 云操作(计算)
    icon: "./media/icon-compute.png"
    url: https://docs.netapp.com/us-en/cloud-manager-compute/index.html
    summary: 深入了解您的云计算支出并确定潜在节省量。
    tags: all, aws, extension
  - title: Cloud Volumes ONTAP
    icon: "./media/icon-cvo.png"
    url: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html
    summary: 让您的云存储更经济实惠，更智能，更合规，更安全。
    tags: all, storage, aws, azure, gcp
  - title: 适用于 AWS 的 Cloud Volumes Service
    icon: "./media/icon-cvs.png"
    url: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-service-aws/index.html
    summary: 具有全闪存性能的 Cloud 原生文件服务。
    tags: all, storage, aws
  - title: 适用于 Google Cloud 的 Cloud Volumes Service
    icon: "./media/icon-cvs.png"
    url: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-service-gcp/index.html
    summary: 保护，保护和加速文件存储。
    tags: all, storage, gcp
  - title: 复制和同步(Cloud Sync)
    icon: "./media/icon-sync.png"
    url: https://docs.netapp.com/us-en/cloud-manager-sync/index.html
    summary: 在内部数据存储和云数据存储之间同步数据。
    tags: all, aws, azure, gcp, mobility
  - title: 数字顾问(Active IQ)
    icon: "./media/icon-activeiq.png"
    url: https://docs.netapp.com/us-en/active-iq/index.html
    tags: all, health
    summary: 提供可操作的智能信息，以实现最佳存储运行状况。
  - title: 数字电子钱包
    icon: "./media/digital-wallet.png"
    url: https://docs.netapp.com/us-en/bluexp-digital-wallet/index.html
    tags: all, governance
    summary: 管理和监控许可证和订阅。
  - title: E系列系统
    icon: "./media/icon-e-series.png"
    url: https://docs.netapp.com/us-en/cloud-manager-e-series/index.html
    summary: 了解E系列系统、全面了解混合多云中的数据。
    tags: all, storage
  - title: 经济效率
    icon: "./media/icon-economic-efficiency.png"
    url: https://docs.netapp.com/us-en/bluexp-economic-efficiency/index.html
    summary: 确定当前或预测的低容量集群、并实施数据分层或其他容量建议。
    tags: all, governance
  - title: 边缘缓存(全局文件缓存)
    icon: "./media/icon-cache.png"
    url: https://docs.netapp.com/us-en/cloud-manager-file-cache/index.html
    summary: 为分布式员工实现实时全局文件共享。
    tags: all, mobility, aws, azure, gcp
  - title: Kubernetes 集群
    icon: "./media/icon-kubernetes.png"
    url: https://docs.netapp.com/us-en/cloud-manager-kubernetes/index.html
    summary: 对混合云中的 Kubernetes 集群进行高级数据管理。
    tags: all, storage, aws, azure
  - title: 内部 ONTAP 集群
    icon: "./media/icon-onprem.png"
    url: https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html
    summary: 使用System Manager和BlueXP的数据服务从BlueXP管理您的NetApp AFF 和FAS 系统。
    tags: all, storage
  - title: 运营故障恢复能力
    icon: "./media/icon-op-resiliency.png"
    url: https://docs.netapp.com/us-en/bluexp-operational-resiliency/index.html
    summary: 实施自动化固件和软件配置风险修复、以保持ONTAP 集群的运行状况。
    tags: all, health
  - title: 勒索软件保护
    icon: "./media/icon-ransomware.png"
    url: https://docs.netapp.com/us-en/cloud-manager-ransomware/index.html
    summary: 评估数据对网络攻击的弹性。
    tags: all, protection
  - title: 修复(AppTemplate)
    icon: "./media/icon-app-template.png"
    url: https://docs.netapp.com/us-en/cloud-manager-app-template/index.html
    summary: 在BlueXP中自动执行操作、以加快配置速度并消除手动工作。
    tags: all, health
  - title: Replication
    icon: "./media/icon-replication.png"
    url: https://docs.netapp.com/us-en/cloud-manager-replication/index.html
    summary: 在存储系统之间复制数据以支持备份和灾难恢复。
    tags: all, protection
  - title: StorageGRID
    icon: "./media/icon-storagegrid.png"
    url: https://docs.netapp.com/us-en/cloud-manager-storagegrid/index.html
    summary: 发现和管理StorageGRID 系统。
    tags: all, storage
  - title: 分层(云分层)
    icon: "./media/icon-tiering.png"
    url: https://docs.netapp.com/us-en/cloud-manager-tiering/index.html
    summary: 将内部 ONTAP 存储扩展到云。
    tags: all, aws, azure, gcp, mobility
